### ISSUE TITLE
PostgreSQL database psycopg2.errors.NotNullViolation: null value in column "translation_key" violates not-null constraint

### ISSUE THREAD

**Issue by ogola89** [coderedcorp/coderedcms#403]
#### Describe the bug
I am just starting out with coderedcms, and have been using it fine. However, I wanted to change the database to using postgresql as my database. However, when I do this (when starting a project from scratch), I am unable to successfully run migrations. Switching back to sqlite works again though, so I am sure it is as a result of my using postgresql.

#### Steps to reproduce
1. coderedcms start <project>
2. cd project
3. Change settings 'base.py' from:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
```
to:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_name',
        'USER': 'xxxxx',
        'PASSWORD': 'xxxxx',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
```
4. Run `python manage.py migrate`
5. This is where the error comes in:
```
psycopg2.errors.NotNullViolation: null value in column "translation_key" violates not-null constraint
DETAIL:  Failing row contains (6, 00010001, 2, 0, Home, home, t, f, /home/, , f, , null, null, f, 9, null, f, null, null, null, null, , null, null, null, null, null).
```

#### Expected behavior
I expect it to successfully run migrations as when it is done on sqlite

#### Additional context
Entire error output:

```
Operations to perform:
  Apply all migrations: admin, auth, coderedcms, contenttypes, sessions, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailredirects, wagtailsearch, wagtailusers, website
Running migrations:
  Applying website.0002_initial_data...Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "translation_key" violates not-null constraint
DETAIL:  Failing row contains (6, 00010001, 2, 0, Home, home, t, f, /home/, , f, , null, null, f, 9, null, f, null, null, null, null, , null, null, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\core\management\commands\migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\migrations\executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\migrations\operations\special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "G:\OneDrive\Academia\Acies-Digital\CodedredCMS\aciesdigital\website\migrations\0002_initial_data.py", line 33, in initial_data
    url_path='/home/',
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\base.py", line 749, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\base.py", line 784, in save_base
    parent_inserted = self._save_parents(cls, using, update_fields)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\base.py", line 812, in _save_parents
    parent_inserted = self._save_parents(cls=parent, using=using, update_fields=update_fields)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\base.py", line 815, in _save_parents
    force_insert=parent_inserted,
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\base.py", line 890, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\base.py", line 929, in _do_insert
    using=using, raw=raw,
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\models\sql\compiler.py", line 1394, in execute_sql
    cursor.execute(sql, params)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\ProgramData\Anaconda3\envs\codered\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "translation_key" violates not-null constraint
DETAIL:  Failing row contains (6, 00010001, 2, 0, Home, home, t, f, /home/, , f, , null, null, f, 9, null, f, null, null, null, null, , null, null, null, null, null).
```

Wagtail version == 2.9.3
Coderedcms version == 0.19.1
Django version == 3.0.11
psycopg2 version == 2.8.6 (dt dec pq3 ext lo64)

**Comment by rcoldiron** [comment]
I set up a project to test this out but I got migrations to work with postgresql. Is "translation_key" a field from one of your models?

**Comment by vsalvino** [comment]
This could possibly be related to the translation updates that were added to wagtail recently.

@ogola89 - if you create a new coderedcms project (in a new folder for example) using:

```console
$ coderedcms start <projectname>
```

Then switch it to postgres... do the migrations work? Or are they also broken?

**Comment by hollstrom** [comment]
I have the same issue. Used to work just fine, but after the latest migration, I cannot save new pages (I get that error message!). Did you find a solution?

**Comment by vsalvino** [comment]
Closing this due to inactivity. Please re-open if any new info becomes available. I would also encourage trying to re-produce this on the latest version of coderedcms... we have done a lot of tech debt work since then. Thanks!
