### ISSUE TITLE
Python manage.py migrate "No module named 'coderedcms'" on macOS Monterey(12.3.1)

### ISSUE THREAD

**Issue by dannkkie** [coderedcorp/coderedcms#489]
Following the installation steps here both for basic and sass  https://docs.coderedcorp.com/wagtail-crx/getting_started/install.html.  

1. python -m venv ./venv/
2. source ./venv/bin/activate
3. pip install coderedcms
4. coderedcms start mysite --sitename "My Company Inc." --domain www.example.com
5. Enter the mysite project with cd mysite/
6. Run python manage.py migrate 
7.Then i get this error message

```
Traceback (most recent call last):
  File "/Users/eddie/PycharmProjects/tgpdProject/mainsite/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'coderedcms'
```

when i run piplist coderedcms is installed. what could be the problem ?......... I used both python 3.9 and 3.10 same issue but worked fine on an ubuntu guest on virtualbox... Kindly help I am using Pycharm Prefessional 2022.1.1(Build #PY-221.5591.52)

**Comment by vsalvino** [comment]
I'm guessing something with PyCharm is not finding the venv, and is using the wrong Python. Unfortunately I am not familiar with PyCharm.

Can you run all of these steps in the terminal, without PyCharm, and let me know if it works on your system "normally"?

**Comment by dannkkie** [comment]
Sure will do that asap

**Comment by dannkkie** [comment]
> I'm guessing something with PyCharm is not finding the venv, and is using the wrong Python. Unfortunately I am not familiar with PyCharm.
> 
> Can you run all of these steps in the terminal, without PyCharm, and let me know if it works on your system "normally"?

Having same issue using terminal

**Comment by dannkkie** [comment]
@vsalvino i just identified the cause of this issue I should be using python3 and pip3…….I have set an alias in zsh python for the systems python so using python and pip without the 3 uses the systems installation instead of using that of the virtualenv
